- name: Initialize Kubernetes and Install CNI
  hosts: all
  become: true

  tasks:
    - name: Initialize Kubernetes Master
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all

    - name: Set up kubectl config for ubuntu user
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Calico CNI
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

    - name: Wait for Calico to initialize
      shell: sleep 20

    - name: Check node status
      shell: kubectl get nodes
